image: qoveryrd/ci:52163e2a8b6454764ce684d5ac9f2d6994283cc0

services:
  - docker:dind

stages:
  - tests

before_script:
  - test -z $KUBERNETES_PORT || export DOCKER_HOST=tcp://127.0.0.1:2375

wip-fast-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh fast_tests
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
  artifacts:
    when: always
    reports:
      junit: qovery-engine/results.xml

wip-full-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_tests
  when: manual
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:/

dev-full-tests:
  stage: tests
  retry: 0
  script:
    - ./helper.sh all_tests
  only:
    refs:
      - dev
