name: tests

on:
  push:
    branches-ignore: [ main, dev ]
  pull_request:
    branches-ignore: [ main, dev ]

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  selected-functionnal-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v1
      - name: Run selected functional tests
        timeout-minutes: 120
        env:
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PERSONAL_TOKEN: ${{ secrets.GITLAB_PERSONAL_TOKEN }}
        run: |
          branch=$(echo ${{github.ref}} | sed -r 's/^refs\/heads\/(.+)/\1/')
          echo "Branch name: $branch"
          export GITHUB_BRANCH=$branch
          export GITHUB_COMMIT_ID=$GITHUB_SHA
          trap "./helper.sh stop_gitlab_pipeline" SIGTERM SIGINT
          ./helper.sh autodetect &
          wait $!